[deps]
DqdLeadsCavity = "9c663722-20cf-451c-a5d1-0d21e07208d9"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
QuantumToolbox = "6c2fb7c5-b903-41d2-bc5e-5a7c320b9fab"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
